In [1]:
import tensorflow as tf
from tensorflow import keras
import pandas as pd
from numpy import mean
from numpy import std
from sklearn.datasets import make_classification
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.ensemble import RandomForestClassifier

In [11]:
TRAIN_FEATURE_URL = "https://raw.githubusercontent.com/weeeeiz/sc/main/21trainfeature.csv"
train_feature_path = tf.keras.utils.get_file("2021trainfeaturesssssssss.csv", TRAIN_FEATURE_URL)

TRAIN_LABEL_URL = "https://raw.githubusercontent.com/weeeeiz/sc/main/21trainlab.csv"
train_label_path = tf.keras.utils.get_file("2021---trainlabelss.csv", TRAIN_LABEL_URL)

TRAIN_ALL_URL = "https://raw.githubusercontent.com/weeeeiz/sc/main/21all.csv"
train_all_path = tf.keras.utils.get_file("2021alls.csv", TRAIN_ALL_URL)

TR_ALL_LABEL_URL = "https://raw.githubusercontent.com/weeeeiz/sc/main/21alllab.csv"
tr_all_label_path = tf.keras.utils.get_file("2021labs.csv", TR_ALL_LABEL_URL)

TEST_FEATURE_URL = "https://raw.githubusercontent.com/weeeeiz/sc/main/21testfeat.csv"
test_feature_path = tf.keras.utils.get_file("21_testfssss.csv", TEST_FEATURE_URL)

TEST_LABEL_URL = "https://raw.githubusercontent.com/weeeeiz/sc/main/21testlab.csv"
test_label_path = tf.keras.utils.get_file("21testlss.csv", TEST_LABEL_URL)

train_feature = pd.read_csv(train_all_path, header = None)
test_feature = pd.read_csv(test_feature_path, header = None)
train_label = pd.read_csv(tr_all_label_path, header = None)
test_label = pd.read_csv(test_label_path, header = None)

8192/151 [==============================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

In [12]:
model = RandomForestClassifier(n_estimators=25, max_depth = None, min_samples_split=2, random_state=1)
model.fit(train_feature, train_label)

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=25,
                       n_jobs=None, oob_score=False, random_state=1, verbose=0,
                       warm_start=False)

In [12]:
pred = model.predict(test_feature)
pred

array([0, 0, 2, 2, 1, 1, 2])

In [13]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(test_label, pred))

Accuracy: 0.7142857142857143


In [14]:
train_feature

0     1      2      3     4      5      6     7      8    9   ...  15  \
0    1.40  4.50   8.50   1.48  4.20   8.50   1.36  4.00   8.30  1.0  ...   8   
1    4.75  3.20   1.91   4.75  3.10   2.00   4.28  2.90   1.90  0.5  ...   2   
2    2.80  3.10   2.75   2.80  3.00   2.70   2.70  2.90   2.60  0.5  ...   6   
3    1.67  3.60   5.75   1.65  3.50   6.00   1.58  3.55   5.25  1.0  ...   3   
4    1.45  4.00   8.50   1.48  4.00   7.50   1.40  3.90   7.40  1.0  ...   6   
5    1.57  4.50   5.00   1.65  3.80   5.50   1.52  3.80   5.40  0.5  ...  10   
6    1.57  2.88  12.00   1.33  5.00  12.00   1.28  4.50  10.00  1.0  ...   6   
7    4.00  3.30   2.05   4.33  3.40   1.95   3.40  3.35   1.95  1.0  ...   1   
8    1.57  3.90   6.50   1.60  3.75   6.00   1.48  3.60   6.60  1.0  ...   3   
9    4.33  3.30   1.95   4.20  3.25   2.05   3.78  3.20   1.88  1.0  ...   5   
10   9.00  4.75   1.36   8.50  4.50   1.40   7.00  4.40   1.35  0.5  ...   1   
11   1.57  4.20   5.50   1.70  3.80   5.00   1.55  3.90   4.90  1.0  ...  10   
12   1.70  3.50   5.75   1.77  3.40   5.75   1.65  3.25   5.25  0.5  ...   3   
13   1.33  5.00  10.00   1.37  5.00  10.00   1.30  4.70   7.90  1.0  ...   5   
14   1.91  3.20   4.75   1.90  3.30   4.50   1.82  3.08   4.32  0.5  ...   4   
15   1.29  5.75  11.00   1.33  5.00  10.00   1.32  4.50   8.00  1.0  ...   5   
16   1.18  6.50  17.00   1.20  6.50  13.00   1.18  6.00  11.00  1.0  ...   9   
17   3.00  3.40   2.40   2.87  3.40   2.40   2.75  3.10   2.35  0.5  ...   4   
18   1.73  3.50   5.25   1.77  3.50   5.50   1.64  3.40   4.90  0.5  ...   6   
19   1.50  4.33   6.50   1.50  4.50   7.00   1.38  4.30   6.60  1.0  ...   7   
20   1.80  3.60   4.75   1.87  3.60   4.50   1.72  3.40   4.35  0.5  ...   8   
21   1.60  3.80   6.00   1.61  4.20   5.75   1.46  4.00   5.80  1.0  ...   4   
22   1.22  6.50  13.00   1.22  6.00  12.00   1.22  5.40   9.50  1.0  ...   7   
23   3.90  2.10   3.10   3.80  2.10   3.10   3.50  2.05   3.00  0.5  ...   1   
24   1.53  4.00   7.00   1.55  4.00   7.50   1.38  4.20   7.00  1.0  ...   2   
25   2.80  2.90   2.90   2.87  3.00   2.87   2.87  3.00   2.87  1.0  ...   4   
26   2.20  3.25   3.50   2.25  3.20   3.40   2.10  3.15   3.20  0.0  ...   2   
27   1.30  5.25  11.00   1.33  5.25  11.00   1.27  4.80   9.00  1.0  ...   1   
28   1.45  4.33   7.50   1.53  3.80   7.50   1.38  4.00   7.70  1.0  ...   3   
29   2.60  3.80   2.45   3.20  3.50   2.20   2.60  3.60   2.24  1.0  ...   3   
30   8.50  4.50   1.40   8.50  4.50   1.45   7.50  4.20   1.36  1.0  ...   3   
31   2.50  3.30   2.88   2.87  3.20   2.70   2.50  3.20   2.55  1.0  ...   1   
32  13.00  5.50   1.25  11.00  5.25   1.30  10.00  4.80   1.25  1.0  ...   3   
33   2.20  3.40   3.30   2.25  3.40   3.40   2.10  3.10   3.27  1.0  ...   7   
34   1.11  9.50  19.00   1.13  8.50  17.00   1.14  6.60  13.00  1.0  ...   7   
35   4.20  3.30   1.95   3.50  3.10   2.20   3.60  3.20   1.95  0.5  ...   5   
36   4.50  3.10   1.95   4.33  3.00   2.05   3.85  3.00   1.95  0.5  ...   1   
37   1.55  3.75   7.00   1.57  3.80   6.50   1.45  3.80   6.60  0.5  ...   6   
38   1.57  4.00   6.00   1.66  3.80   5.50   1.42  4.10   6.30  0.5  ...   0   
39   2.40  3.30   3.00   2.38  3.40   3.00   2.20  3.15   3.00  0.5  ...   1   
40   6.50  3.90   1.57   6.50  3.80   1.60   6.40  3.80   1.46  0.5  ...   7   
41   1.60  3.80   6.00   1.66  3.75   5.50   1.52  3.60   5.90  0.5  ...   8   
42   2.38  3.30   3.10   2.30  3.30   3.10   2.40  3.25   2.62  1.0  ...   4   
43   2.30  3.20   3.30   2.30  3.20   3.30   2.18  3.10   3.10  0.5  ...   3   
44   5.75  3.90   1.62   5.50  3.80   1.65   5.25  3.90   1.50  0.5  ...   2   
45   3.40  3.20   2.25   3.40  3.20   2.25   2.95  3.00   2.30  0.5  ...   4   
46   4.00  3.00   2.15   3.80  3.20   2.05   3.40  3.02   2.08  0.5  ...   5   
47   7.50  4.00   1.50   7.50  3.80   1.53   7.10  4.00   1.40  0.5  ...   2   
48   2.50  3.10   3.10   2.40  3.20   3.10   2.20  3.10   3.06  0.5  ...   4   
49   1.

In [8]:
New_FEATURE_URL = "https://raw.githubusercontent.com/weeeeiz/sc/main/pred.csv"
new_feature_path = tf.keras.utils.get_file("new_featsss.csv", New_FEATURE_URL)
new_feature = pd.read_csv(new_feature_path, header = None)

8192/649 [==========================================================================================================================================================================================================================================================================================================================================================================================] - 0s 1us/step


In [9]:
new_feature

0    1     2     3    4     5     6     7     8    9   ...         15  \
0  5.75  3.9  1.62  5.50  3.8  1.65  5.25  3.90  1.50  0.5  ...   2.000000   
1  3.40  3.2  2.25  3.40  3.2  2.25  2.95  3.00  2.30  0.5  ...   4.000000   
2  4.00  3.0  2.15  3.80  3.2  2.05  3.40  3.02  2.08  0.5  ...   5.000000   
3  7.50  4.0  1.50  7.50  3.8  1.53  7.10  4.00  1.40  0.5  ...   2.000000   
4  2.50  3.1  3.10  2.40  3.2  3.10  2.20  3.10  3.06  0.5  ...   4.000000   
5  1.70  3.6  5.50  1.72  3.6  5.25  1.60  3.45  5.20  1.0  ...  10.000000   
6  2.63  3.0  3.00  2.60  3.0  3.00  2.48  2.95  2.75  1.0  ...   4.333333   

   16          17          18         19  20        21        22  23  24  
0  10   85.000000  203.000000  15.000000  14  2.000000  1.000000  13   6  
1   3   87.000000  116.000000  16.000000  13  1.000000  2.000000   1   7  
2   7  106.000000  103.000000  16.000000  11  2.000000  0.000000  40  10  
3   6   95.000000  119.000000  10.000000   4  0.000000  0.000000  24   4  
4   3   70.000000  189.000000  17.000000  18  2.000000  1.000000   7   6  
5   3  166.000000  117.000000  10.000000  21  1.000000  1.000000   4  10  
6   5  120.833333  116.333333   9.666667  12  0.833333  1.166667   4   7  

[7 rows x 25 columns]

In [13]:
pred = model.predict(new_feature)
pred

array([2, 1, 1, 1, 2, 2, 1])

In [17]:
cropor_URL = "https://raw.githubusercontent.com/weeeeiz/sc/main/dataset/CROPOR.csv"
cropor_path = tf.keras.utils.get_file("cropor_feats.csv", cropor_URL)
cropor = pd.read_csv(cropor_path, header = None)
pred1 = model.predict(cropor)
pred1

array([0])

In [20]:
cropor

0   1    2     3     4    5    6    7     8    9   ...  15  16  17  18  \
0  2.87   3  2.9  2.88  2.95  2.9  2.7  3.1  2.75  0.5  ...   3   7  61  70   

          19  20        21        22  23  24  
0  11.666667  10  2.666667  0.666667  27   8  

[1 rows x 25 columns]

In [18]:
WALNIR_URL = "https://raw.githubusercontent.com/weeeeiz/sc/main/dataset/WALNIR.csv"
WALNIR_path = tf.keras.utils.get_file("walnir_feats.csv", WALNIR_URL)
walnir = pd.read_csv(WALNIR_path, header = None)
pred2 = model.predict(walnir)
pred2

array([0])

In [21]:
walnir

0    1     2     3   4     5     6    7   8    9   ...        15  \
0  2.15  2.9  4.75  2.05   3  4.75  1.91  3.1   5  0.5  ...  5.333333   

         16         17         18         19         20        21        22  \
0  1.666667  59.666667  53.666667  10.333333  11.666667  0.666667  1.333333   

   23  24  
0  26  25  

[1 rows x 25 columns]

In [23]:
HUNBEL_URL = "https://raw.githubusercontent.com/weeeeiz/sc/main/dataset/HUNBEL.csv"
HUNBEL_path = tf.keras.utils.get_file("hunbel_featus.csv", HUNBEL_URL)
hunbel = pd.read_csv(HUNBEL_path, header = None)
pred3 = model.predict(hunbel)
pred3

8192/172 [==============================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

array([0])

In [22]:
hunbel

0    1     2    3    4     5   6    7     8    9   ...        15        16  \
0   7  3.6  1.65  6.5  3.6  1.67   7  3.6  1.59  0.5  ...  4.333333  4.666667   

          17         18         19         20        21        22  23  24  
0  59.666667  57.333333  14.666667  10.666667  2.666667  1.333333  20   2  

[1 rows x 25 columns]

In [25]:
New_FEATURE_URL = "https://raw.githubusercontent.com/weeeeiz/sc/main/dataset/16f.csv"
new_feature_path = tf.keras.utils.get_file("newfeatures.csv", New_FEATURE_URL)
new_feature = pd.read_csv(new_feature_path, header = None)
pred3 = model.predict(new_feature)
pred3

8192/1179 [================================================================================================================================================================================================================] - 0s 0us/step


array([2, 0, 0, 0, 0, 2, 0, 2])